#!/usr/bin/python -u
import sys
import re
import os

commands = []
while True:
    line = sys.stdin.readline()
    if not line:
        break
    m = re.match(r'(?P<fn>.+?):(?P<ln>.+?):.+',line)
    if m:
        c = 'vim '+m.group('fn')+' +'+m.group('ln')
        print c
        commands.append(c)

for c in commands:
    rt = os.system(c.strip() +" > /dev/tty < /dev/tty");
    if rt != 0:
        break;
